services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: 2529
      POSTGRES_DB: users
      PGDATA: /data/postgres
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_HOST_AUTH_METHOD: trust
    command: ["postgres", "-c", "log_statement=all", "-c", "log_connections=on"]
    volumes:
      - postgres:/data/postgres
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  cache:
    image: redis:latest
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    container_name: minio
    image: 'minio/minio'
    command: server /data --console-address ":9001"
    volumes:
      - 'minio_data:/data'
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: auth/Dockerfile
    env_file:
      - .env
    environment:
      GRPC_PORT: 50051
      JWT_SECRET: "${JWT_TOKEN}"
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
      cache:
        condition: service_healthy

  file-service:
    build:
      context: .
      dockerfile: file/Dockerfile
    env_file:
      - .env
    environment:
      GRPC_PORT: 50052
      AUTH_SERVICE_ADDR: "auth-service:50051"
    ports:
      - "50052:50052"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      auth-service:
        condition: service_started

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    env_file:
      - .env
    environment:
      PORT: 8080
      AUTH_SERVICE_ADDR: "auth-service:50051"
      FILE_SERVICE_ADDR: "file-service:50052"
    ports:
      - "8080:8080"
    depends_on:
      auth-service:
        condition: service_started
      file-service:
        condition: service_started

volumes:
  minio_data:
  postgres:
  cache:
    driver: local