services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: 2529
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  cache:
    image: redis:latest
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  minio:
    container_name: minio
    image: 'bitnami/minio:latest'
    volumes:
      - 'minio_data:/data'
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_USE_SSL: "${MINIO_USE_SSL}"
      MINIO_DEFAULT_BUCKETS: "${MINIO_BUCKET_NAME}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]

  auth-service:
    build:
      context: .
      dockerfile: auth/Dockerfile
    env_file:
      - .env
    environment:
      GRPC_PORT: 50051
      JWT_SECRET: "${JWT_TOKEN}"
    ports:
      - "50051:50051"
    depends_on:
      - postgres
      - cache

  file-service:
      build:
        context: .
        dockerfile: file/Dockerfile
      env_file:
        - .env
      environment:
        GRPC  _PORT: 50052
        AUTH_SERVICE_ADDR: "auth-service:50051"
      ports:
        - "50052:50052"
      depends_on:
        - auth-service
        - postgres
        - minio

volumes:
  minio_data:
  postgres:
  cache:
    driver: local